version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./tcapy:/tcapy/tcapy:ro
      - ./tcapygen:/tcapy/tcapygen:ro
      - ./artifacts:/tcapy/artifacts
      - ./source:/source:ro
    env_file: .tcapy.env
    environment:
      - APP_ENV=docker
    depends_on:
      - celery
      - redis
      - memcached
      - mongo
      - mysql

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    working_dir: /tcapy
    command: "celery -A tcapy.conf.celery_calls worker --purge --discard --loglevel=debug -Q celery --concurrency=14 -f test_celery.log"
    env_file: .tcapy.env
    environment:
      - APP_ENV=docker
      - C_FORCE_ROOT=true
    depends_on:
      - redis
      - mongo
      - mysql
      - memcached

  redis:
    image: "redis:alpine"
    command: redis-server --port 6379 --save ""
    ports:
      - 6379:6379

  memcached:
    image: memcached
    ports:
      - 11211:11211

  mongo:
    image: mongo:latest
    env_file: .tcapy.env
    ports:
      - 27017:27017

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: .tcapy.env
    environment:
      - MYSQL_DATABASE=trade_database_test_harness
    ports:
      - 3306:3306